-- DrivePortal v1.8 uitbreiding: pakket/uren, afspraaktype en volledige leskaart
-- Eenmalig uitvoeren in Supabase SQL Editor vóór de nieuwe ZIPs worden gebruikt.

alter table public.portal_appointments add column if not exists appointment_type text;
alter table public.portal_appointments add column if not exists duration_minutes integer;

create table if not exists public.portal_training_summary (
  student_id uuid primary key references public.portal_students(id) on delete cascade,
  package_name text,
  package_minutes integer,
  driven_minutes integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.portal_score_history (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.portal_students(id) on delete cascade,
  module_key text not null,
  module_name text not null,
  module_sort integer not null default 0,
  item_key text not null,
  item_name text not null,
  item_sort integer not null default 0,
  lesson_date date not null,
  score integer not null check (score between 1 and 8),
  unique(student_id,item_key,lesson_date)
);
create index if not exists portal_score_history_student_date_idx on public.portal_score_history(student_id,lesson_date);

alter table public.portal_training_summary enable row level security;
alter table public.portal_score_history enable row level security;

drop policy if exists "student read own training summary" on public.portal_training_summary;
create policy "student read own training summary" on public.portal_training_summary for select to authenticated using (
  exists(select 1 from public.portal_students ps where ps.id=student_id and ps.auth_user_id=auth.uid())
);
drop policy if exists "student read own score history" on public.portal_score_history;
create policy "student read own score history" on public.portal_score_history for select to authenticated using (
  exists(select 1 from public.portal_students ps where ps.id=student_id and ps.auth_user_id=auth.uid())
);

-- DrivePlan-beheerder mag synchroniseren. Pas alleen aan als het beheerdersaccount een ander e-mailadres gebruikt.
drop policy if exists "instructor manage training summary" on public.portal_training_summary;
create policy "instructor manage training summary" on public.portal_training_summary for all to authenticated using ((auth.jwt()->>'email')='rijschooldenhartog@gmail.com') with check ((auth.jwt()->>'email')='rijschooldenhartog@gmail.com');
drop policy if exists "instructor manage score history" on public.portal_score_history;
create policy "instructor manage score history" on public.portal_score_history for all to authenticated using ((auth.jwt()->>'email')='rijschooldenhartog@gmail.com') with check ((auth.jwt()->>'email')='rijschooldenhartog@gmail.com');

grant select on public.portal_training_summary to authenticated;
grant select on public.portal_score_history to authenticated;
grant insert,update,delete on public.portal_training_summary to authenticated;
grant insert,update,delete on public.portal_score_history to authenticated;
grant usage,select on sequence public.portal_score_history_id_seq to authenticated;
